spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smallspace?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&serverTimezone=UTC
    username: root
    password: abc4196853719@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8088



